name: Run Stock Analysis

on:
  schedule:
    # Runs daily at 10am AEST (which is 12am UTC)
    - cron: '0 0 * * *'

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Check Python version  # This will help us debug if Python is set up correctly
      run: python --version

    - name: Create and activate virtual environment  # Create and activate a virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install requests

    - name: Verify installed packages in virtual environment  # Ensure requests is installed in the venv
      run: |
        source venv/bin/activate
        pip freeze

    - name: Run Analysis Script in virtual environment
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        source venv/bin/activate
        python analysis_fetch_200_Final.py
        # Move the generated HTML files into the appropriate folders
        mv *.html Basic/
        mv *.html "Basic Pro"/
        mv *.html Premium/
