name: Run Stock Analysis

on:
  schedule:
    # Runs daily at 9am AEST (which is 11pm UTC)
    - cron: '0 23 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Script
        env:
          OPENAI: ${{ secrets.OPENAI }}  # Pass the secret 'OPENAI' to the script
        run: |
          mkdir -p Basic "Basic Pro" Premium  # Ensure the directories exist
          python analysis_fetch_200_Final.py
          mv *.html Basic/
          mv *.html "Basic Pro"/
          mv *.html Premium/

      - name: List generated files and folders (for debugging)
        run: |
          ls -al
          ls -al Basic/
          ls -al "Basic Pro"/
          ls -al Premium/
