name: Run Stock Analysis

on:
  schedule:
    # Runs daily at midday AEST (which is 2am UTC)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Verify installed packages
      run: pip freeze

    - name: Check OpenAI Key
      run: echo $OPENAI_API_KEY
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    - name: Run Analysis Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python analysis_fetch_200_Final.py
        mv *.html Basic/
        mv *.html "Basic Pro"/
        mv *.html Premium/
