name: Run Stock Analysis

on:
  schedule:
    # Runs daily at 10am AEST (which is 12am UTC)
    - cron: '0 0 * * *'

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Check Python version and paths  # Check Python setup
      run: |
        which python
        python --version
        which pip
        pip --version

    - name: Install dependencies  # Install pip and requests explicitly
      run: |
        python -m pip install --upgrade pip
        python -m pip install requests

    - name: Verify installed packages  # Ensure requests is installed
      run: pip freeze

    - name: Run Analysis Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python analysis_fetch_200_Final.py
        # Move the generated HTML files into the appropriate folders
        mv *.html Basic/
        mv *.html "Basic Pro"/
        mv *.html Premium/
