name: Run Stock Analysis

on:
  schedule:
    # Runs Monday to Friday at 9am AEST (which is 11pm UTC)
    - cron: '0 23 * * 1-5'
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the runner can write to the repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create directories
        run: |
          mkdir -p Basic "Basic Pro" Premium

      - name: Run Analysis Script
        env:
          OPENAI: ${{ secrets.OPENAI }}
        run: python analysis_fetch_200_Final.py

      - name: Copy HTML files to other directories
        run: |
          # Copy all HTML files to Basic, Basic Pro, and Premium daily
          cp Premium/*.html Basic/
          cp Premium/*.html "Basic Pro"/
