name: Run Stock Analysis

on:
  schedule:
    # Schedule run (e.g., daily at 10am UTC)
    - cron: '0 10 * * *'
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Analysis Script
        env:
          OPENAI: ${{ secrets.OPENAI }}  # Pass the secret 'OPENAI' to the script
        run: python analysis_fetch_200_Final.py
